2024-08-09 07:53:02,258 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.6:37893'
2024-08-09 07:53:02,854 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-nu6fqwzc', purging
2024-08-09 07:53:03,379 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.6:36193
2024-08-09 07:53:03,379 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.6:36193
2024-08-09 07:53:03,379 - distributed.worker - INFO -           Worker name:             SLURMCluster-3
2024-08-09 07:53:03,379 - distributed.worker - INFO -          dashboard at:           10.34.59.6:44999
2024-08-09 07:53:03,379 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:33137
2024-08-09 07:53:03,380 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:53:03,380 - distributed.worker - INFO -               Threads:                          1
2024-08-09 07:53:03,380 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 07:53:03,380 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-c06xnb56
2024-08-09 07:53:03,380 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:53:03,788 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 07:53:03,789 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:33137
2024-08-09 07:53:03,789 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 07:53:03,789 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:33137
2024-08-09 07:54:03,784 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.6:36193. Reason: scheduler-close
2024-08-09 07:54:03,785 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:46758 remote=tcp://10.34.59.1:33137>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.6:46758 remote=tcp://10.34.59.1:33137>: Stream is closed
2024-08-09 07:54:03,789 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.6:37893'. Reason: scheduler-close
slurmstepd: error: *** JOB 2331216 ON cl-node006 CANCELLED AT 2024-08-09T07:54:03 ***
