2024-08-09 08:11:15,700 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.10:45191'
2024-08-09 08:11:16,296 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-onm9zcfs', purging
2024-08-09 08:11:16,771 - distributed.worker - INFO -       Start worker at:    tcp://10.34.59.10:43235
2024-08-09 08:11:16,771 - distributed.worker - INFO -          Listening to:    tcp://10.34.59.10:43235
2024-08-09 08:11:16,771 - distributed.worker - INFO -           Worker name:             SLURMCluster-2
2024-08-09 08:11:16,771 - distributed.worker - INFO -          dashboard at:          10.34.59.10:45968
2024-08-09 08:11:16,771 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:45504
2024-08-09 08:11:16,771 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:11:16,771 - distributed.worker - INFO -               Threads:                          1
2024-08-09 08:11:16,771 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 08:11:16,771 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-4hxzxa02
2024-08-09 08:11:16,771 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:11:17,126 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 08:11:17,126 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:45504
2024-08-09 08:11:17,127 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 08:11:17,127 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:45504
slurmstepd: error: *** JOB 2331340 ON cl-node010 CANCELLED AT 2024-08-09T08:11:53 ***
2024-08-09 08:11:53,178 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.10:43235. Reason: scheduler-close
2024-08-09 08:11:53,179 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:51572 remote=tcp://10.34.59.1:45504>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.10:51572 remote=tcp://10.34.59.1:45504>: Stream is closed
2024-08-09 08:11:53,183 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.10:45191'. Reason: scheduler-close
2024-08-09 08:11:53,185 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:45504; closing.
2024-08-09 08:11:53,185 - distributed.nanny - INFO - Worker closed
