2024-08-09 06:54:31,615 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.2:34791'
2024-08-09 06:54:32,211 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-4jis2ipu', purging
2024-08-09 06:54:32,858 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.2:46573
2024-08-09 06:54:32,858 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.2:46573
2024-08-09 06:54:32,858 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2024-08-09 06:54:32,858 - distributed.worker - INFO -          dashboard at:           10.34.59.2:40400
2024-08-09 06:54:32,858 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:33506
2024-08-09 06:54:32,858 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:54:32,858 - distributed.worker - INFO -               Threads:                          1
2024-08-09 06:54:32,858 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 06:54:32,858 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-q2iuc0k9
2024-08-09 06:54:32,858 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:54:33,395 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 06:54:33,395 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:33506
2024-08-09 06:54:33,395 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 06:54:33,396 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:33506
slurmstepd: error: *** JOB 2331136 ON cl-node002 CANCELLED AT 2024-08-09T06:57:31 ***
2024-08-09 06:57:31,450 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.2:46573. Reason: scheduler-close
2024-08-09 06:57:31,452 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:39688 remote=tcp://10.34.59.1:33506>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:39688 remote=tcp://10.34.59.1:33506>: Stream is closed
2024-08-09 06:57:31,458 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.2:34791'. Reason: scheduler-close
2024-08-09 06:57:31,461 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:33506; closing.
2024-08-09 06:57:31,461 - distributed.nanny - INFO - Worker closed
