2024-08-09 04:16:05,800 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.2:33403'
2024-08-09 04:16:06,392 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-vx477lgt', purging
2024-08-09 04:16:06,863 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.2:44782
2024-08-09 04:16:06,863 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.2:44782
2024-08-09 04:16:06,863 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2024-08-09 04:16:06,863 - distributed.worker - INFO -          dashboard at:           10.34.59.2:46192
2024-08-09 04:16:06,863 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:37371
2024-08-09 04:16:06,863 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:16:06,863 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:16:06,863 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:16:06,863 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-8l2ey07r
2024-08-09 04:16:06,863 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:16:07,216 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:16:07,216 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:37371
2024-08-09 04:16:07,217 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:16:07,217 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:37371
slurmstepd: error: *** JOB 2328896 ON cl-node002 CANCELLED AT 2024-08-09T04:16:17 ***
2024-08-09 04:16:17,805 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.2:44782. Reason: scheduler-close
2024-08-09 04:16:17,806 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:35742 remote=tcp://10.34.59.1:37371>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:35742 remote=tcp://10.34.59.1:37371>: Stream is closed
2024-08-09 04:16:17,809 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.2:33403'. Reason: scheduler-close
2024-08-09 04:16:17,811 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:37371; closing.
2024-08-09 04:16:17,811 - distributed.nanny - INFO - Worker closed
