2024-08-09 04:25:02,167 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.9:41362'
2024-08-09 04:25:02,761 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-a8ybcqda', purging
2024-08-09 04:25:03,273 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.9:34380
2024-08-09 04:25:03,273 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.9:34380
2024-08-09 04:25:03,273 - distributed.worker - INFO -           Worker name:             SLURMCluster-5
2024-08-09 04:25:03,273 - distributed.worker - INFO -          dashboard at:           10.34.59.9:45300
2024-08-09 04:25:03,273 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:46808
2024-08-09 04:25:03,273 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:25:03,273 - distributed.worker - INFO -               Threads:                          1
2024-08-09 04:25:03,273 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 04:25:03,273 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-jlnrm59_
2024-08-09 04:25:03,273 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:25:03,664 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 04:25:03,665 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:46808
2024-08-09 04:25:03,665 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 04:25:03,665 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:46808
slurmstepd: error: *** JOB 2329014 ON cl-node009 CANCELLED AT 2024-08-09T04:25:12 ***
2024-08-09 04:25:12,124 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.9:34380. Reason: scheduler-close
2024-08-09 04:25:12,126 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.9:43844 remote=tcp://10.34.59.1:46808>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.9:43844 remote=tcp://10.34.59.1:46808>: Stream is closed
2024-08-09 04:25:12,129 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.9:41362'. Reason: scheduler-close
2024-08-09 04:25:12,132 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:46808; closing.
2024-08-09 04:25:12,132 - distributed.nanny - INFO - Worker closed
