2024-08-09 05:41:39,652 - distributed.nanny - INFO -         Start Nanny at: 'tcp://10.34.59.2:40070'
2024-08-09 05:41:40,248 - distributed.diskutils - INFO - Found stale lock file and directory '/tmp/dask-scratch-space/worker-e8i7gfi4', purging
2024-08-09 05:41:40,898 - distributed.worker - INFO -       Start worker at:     tcp://10.34.59.2:33257
2024-08-09 05:41:40,898 - distributed.worker - INFO -          Listening to:     tcp://10.34.59.2:33257
2024-08-09 05:41:40,898 - distributed.worker - INFO -           Worker name:             SLURMCluster-0
2024-08-09 05:41:40,898 - distributed.worker - INFO -          dashboard at:           10.34.59.2:35118
2024-08-09 05:41:40,898 - distributed.worker - INFO - Waiting to connect to:     tcp://10.34.59.1:43165
2024-08-09 05:41:40,898 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 05:41:40,898 - distributed.worker - INFO -               Threads:                          1
2024-08-09 05:41:40,898 - distributed.worker - INFO -                Memory:                   1.86 GiB
2024-08-09 05:41:40,898 - distributed.worker - INFO -       Local Directory: /tmp/dask-scratch-space/worker-p78iom_c
2024-08-09 05:41:40,898 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 05:41:41,420 - distributed.worker - INFO - Starting Worker plugin shuffle
2024-08-09 05:41:41,420 - distributed.worker - INFO -         Registered to:     tcp://10.34.59.1:43165
2024-08-09 05:41:41,421 - distributed.worker - INFO - -------------------------------------------------
2024-08-09 05:41:41,421 - distributed.core - INFO - Starting established connection to tcp://10.34.59.1:43165
slurmstepd: error: *** JOB 2330363 ON cl-node002 CANCELLED AT 2024-08-09T05:43:20 ***
2024-08-09 05:43:20,064 - distributed.worker - INFO - Stopping worker at tcp://10.34.59.2:33257. Reason: scheduler-close
2024-08-09 05:43:20,065 - distributed.batched - INFO - Batched Comm Closed <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:59862 remote=tcp://10.34.59.1:43165>
Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 297, in write
    raise StreamClosedError()
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/batched.py", line 115, in _background_send
    nbytes = yield coro
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/tornado/gen.py", line 767, in run
    value = future.result()
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 307, in write
    convert_stream_closed_error(self, e)
  File "/users/stud/k/kruret00/.local/lib/python3.10/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Worker->Scheduler local=tcp://10.34.59.2:59862 remote=tcp://10.34.59.1:43165>: Stream is closed
2024-08-09 05:43:20,070 - distributed.nanny - INFO - Closing Nanny gracefully at 'tcp://10.34.59.2:40070'. Reason: scheduler-close
2024-08-09 05:43:20,073 - distributed.core - INFO - Received 'close-stream' from tcp://10.34.59.1:43165; closing.
2024-08-09 05:43:20,074 - distributed.nanny - INFO - Worker closed
